"""add_template_type_column

Revision ID: f72caae046ad
Revises: bc08399fb997
Create Date: 2026-05-12 19:22:36.710498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72caae046ad'
down_revision: Union[str, Sequence[str], None] = 'bc08399fb997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('html_template_path', sa.String(length=500), nullable=True))
    op.add_column('templates', sa.Column('template_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'template_type')
    op.drop_column('templates', 'html_template_path')
    # ### end Alembic commands ###
